Add support for AdvantageScope telemetry
Raptacon/Robot-2024 pull request #51
Opened 2024-02-13 02:25 UTC by DanteSGarrett

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issue(s)
Issue: <#X or issue-XX > [REMOVE THIS WHEN DONE Describe the issue you're working on here so it ties to the issue and Kanban (IMPORTANT FOR TRACKING). Make sure to create an issue if one doesn't already exist! ]

## Steps to Test
[ Describe how to run your AUTOMATED TESTS and any manual tests that may be need to prove your fix/feature REMOVE THIS WHEN DONE]
1. [First Step]
2. [Second Step]
3. [and so on...]

## Changelog

[ A brief description of the problem statement. REMOVE THIS WHEN DONE ]

## What?

[ Explain the technical implementation of what you're doing. REMOVE THIS WHEN DONE ]

## Why?

[ Explain why you're making this change and what benefits from it. REMOVE THIS WHEN DONE ]

2024-02-25 16:35 UTC, ChrisHirsch commented on robotswerve.py
> +        if True:
We should probably expose this via the dashboard...default it to true and allow drivers to turn it off? Actually let's do this instead: initially default it false so we can get a feel for it, how it performs, etc and if we like what we're seeing we can change the default to true and eventually just remove the option completely.

2024-02-25 16:36 UTC, ChrisHirsch commented on subsystem/swerveDriveTrain.py
> +    kWheelBaseMeters = 0.7112 # front to back distance
Let's make sure this isn't your change. Main should have the latest which I THINK is 0.5461...but @tuffinmuffin @DarthCooper can you confirm?

2024-02-25 16:39 UTC, ChrisHirsch commented on subsystem/swerveDriveTrain.py
> +        self.updateOdometry()
Should this be in this changeset or is updateOdometry() from another branch? If the latter, we can help get this cleaned up so this is ONLY for telemetry.

2024-02-25 16:39 UTC, ChrisHirsch commented on subsystem/swerveIntakePivot.py
> +import math
Should this be in this changeset or is swerveIntakePivot from another branch? If the latter, we can help get this cleaned up so this is ONLY for telemetry.

2024-02-25 16:40 UTC, ChrisHirsch commented on subsystem/swerveIntakePivotController.py
> +import commands2
Should this be in this changeset or is swerveIntakePivotController from another branch? If the latter, we can help get this cleaned up so this is ONLY for telemetry.

2024-02-25 16:40 UTC, ChrisHirsch commented on swerve/swerveModule.py
> +        self.steerAngle = 0.0
Should this be in this changeset or are the changes to swerveModule from another branch? If the latter, we can help get this cleaned up so this is ONLY for telemetry.

2024-02-25 16:43 UTC, ChrisHirsch requested changes
Please review the change to expose telemetry to the dashboard (default is false to start with and we can explicitly enable during practice and a match or two. Assuming nothing bad happens we will flip it to a default of true)

If those other files aren't supposed to be part of the merge request, let's get those out of this merge request to make it clean.

2024-03-01 00:04 UTC, ChrisHirsch commented
@DanteSGarrett I believe this is now deprecated in favor of your Telemetry PR https://github.com/Raptacon/Robot-2024/pull/57 right?

2024-09-05 01:13 UTC, raylmorris commented
@DanteSGarrett this branch is deprecated and can be deleted, correct? Overcome by #57?

2025-01-18 01:13 UTC, ChrisHirsch commented
Talked with @Sydmen this is completed and merged

2025-01-18 01:13 UTC, closed without merging